# Generated by Django 4.2.25 on 2025-10-23 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.IntegerField(unique=True)),
                ('cpf_aluno', models.CharField(max_length=15, unique=True)),
                ('nome_aluno', models.CharField(max_length=100)),
                ('email_aluno', models.EmailField(max_length=254)),
                ('endereco', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=15)),
                ('data_nascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_ciclo', models.CharField(max_length=50)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('descricao_ciclo', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=30)),
                ('ano_referencia', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_curso', models.CharField(max_length=100)),
                ('carga_horaria', models.IntegerField()),
                ('descricao_curso', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_instrutor', models.CharField(max_length=11, unique=True)),
                ('nome_instrutor', models.CharField(max_length=100)),
                ('email_instrutor', models.EmailField(max_length=254)),
                ('endereco', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=15)),
                ('data_nascimento', models.DateField()),
                ('especialidade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_turma', models.CharField(max_length=50)),
                ('turno', models.CharField(max_length=20)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turmas', to='app.ciclo')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turmas', to='app.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipo', models.CharField(max_length=50)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='app.aluno')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alunos', to='app.turma'),
        ),
        migrations.CreateModel(
            name='InstrutorTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_turma', models.DateTimeField()),
                ('data_inicio', models.DateField()),
                ('instrutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.instrutor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.turma')),
            ],
            options={
                'unique_together': {('instrutor', 'turma')},
            },
        ),
    ]
